### ISSUE TITLE
Running xulpymoney from Gentoo ebuild, without dev environment give this error

### ISSUE THREAD

**Issue by Turulomio** [Turulomio/xulpymoney#2]
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.5/xulpymoney", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 3098, in <module>
    @_call_aside
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 3082, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 3111, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PyQt5' distribution was not found and is required by xulpymoney

I found in Internet https://github.com/jopohl/urh/issues/206

**Comment by Turulomio** [comment]
+
+python_prepare_all() {
+	# remove the PyQt5 dependency
+	# because PyQt5 in Gentoo does not provide egg-info
+	# see also: https://github.com/pyqt/python-qt5/issues/18
+	sed "s:'PyQt5 [^ ]*::" -i setup.py || die
+
+	distutils-r1_python_prepare_all
+}+
+python_prepare_all() {
+	# remove the PyQt5 dependency
+	# because PyQt5 in Gentoo does not provide egg-info
+	# see also: https://github.com/pyqt/python-qt5/issues/18
+	sed "s:'PyQt5 [^ ]*::" -i setup.py || die
+
+	distutils-r1_python_prepare_all
+}

**Comment by Turulomio** [comment]
Linux pip install hasn't PyQt5 dependencies
